#!/bin/bash

if [[ ! $(pidof rofi) ]]; then
	rofi -show combi -modes combi -combi-modes "window,drun,run"
else
	killall rofi
fi

# STYLE="$HOME/.config/hypr/wofi/style.css"

# if [[ ! $(pidof wofi) ]]; then
# 	wofi --show run --style $STYLE
# else
# 	killall wofi
# fi
