#!/bin/bash

if [[ ! $(pidof rofi) ]]; then
	# rofi -show combi -modes combi -combi-modes "window,drun,run"
	# copy wallpaper
	cp $(cat $HOME/.config/hypr/hyprpaper/config/current.conf) $HOME/.config/rofi/images/custom.png
	/home/ayman/.config/rofi/launchers/type-7/launcher.sh
else
	killall rofi
fi
