#!/bin/bash

# This is a Bash script for OneDrive

# onedriveDir="$HOME/OneDrive"
# config="$HOME/.config/hypr/onedrive/foot.ini"
# script="$HOME/.config/hypr/onedrive/bash_script"

# echo 1

/bin/zsh -c '(cat ~/.cache/wal/sequences &); ranger $HOME/OneDrive'

# foot $script
# -D $onedriveDir
