#!/bin/bash

hypr_dir="$HOME/.config/hypr"                               # Hypr directory
css_file="$HOME/.cache/wal/colors.css"                      # CSS file generated by pywal
hyprland_border_file="$hypr_dir/configs/custom/border.conf" # Border config file
dunst_file="$hypr_dir/notifications/dunstrc"                # Dunst config file

# Extract hex color codes from CSS file and store them in an array
colors=($(grep -o '#[0-9A-Fa-f]\{6\}' $css_file | sed 's/^#//'))

for color in "${colors[@]}"; do
    echo "$color"
done

# Define the new string
new_colors="rgb(${colors[3]}) rgb(${colors[4]}) rgb(${colors[5]}) rgb(${colors[6]}) 270deg"

echo -e "general { \n\tcol.active_border = $new_colors \n}" >$hyprland_border_file
