hl.layer_rule({ match = { namespace = "quickshell" }, blur = true })
hl.layer_rule({ match = { namespace = "quickshell" }, blur_popups = true })
hl.layer_rule({ match = { namespace = "quickshell" }, ignore_alpha = 0.1 })

hl.layer_rule({ match = { namespace = "hyprpaper" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "mpvpaper" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "selection" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "user-panel" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "hyprpicker" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "app-launcher" }, animation = "fade" })
