// payment-webhook-kofi — Ko-fi webhook receiver (unauthenticated).
//
// Per Ko-fi docs (help.ko-fi.com "Does Ko-fi have an API or webhook?",
// ko-fi.com/manage/webhooks): Ko-fi POSTs application/x-www-form-urlencoded
// with a single `data` field holding a JSON string. The JSON carries
// verification_token (compared to our KOFI_VERIFICATION_TOKEN secret),
// `type` (Donation / Subscription / Shop Order / Commission), message_id,
// kofi_transaction_id, email, amount, currency, message, timestamp, ...
// Return 200 on handled/skipped deliveries (Ko-fi retries otherwise with the
// same message_id, so processing is idempotent via a unique constraint).
//
// Only type == "Donation" with is_subscription_payment falsy grants value
// (one-time payments only). Shop orders / commissions / subscriptions are
// acknowledged but skipped.
// User association: Ko-fi offers no secure user reference, so the donor puts
// their ArchEclipse link code (AE-XXXX-XXXX) in the donation message. Without
// a valid unused code the payment is stored UNCLAIMED (verified email kept)
// and the donor can claim it from the shell via the email-claim RLS policy.
// Email alone NEVER auto-grants supporter status.

import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.44.4";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const KOFI_TOKEN = Deno.env.get("KOFI_VERIFICATION_TOKEN") ?? "";

// Matches codes generated by the shell: AE-XXXX-XXXX, unambiguous alphabet
// (no 0/O, 1/I/L). Case-insensitive; dashes/spaces optional when pasted.
const CODE_RE = /AE[\s-]*([A-HJ-NP-Z2-9]{4})[\s-]*([A-HJ-NP-Z2-9]{4})/i;

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length || a.length === 0) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

function extractCode(message: unknown): string | null {
  const m = String(message ?? "").toUpperCase().match(CODE_RE);
  if (!m) return null;
  return `AE-${m[1]}-${m[2]}`;
}

serve(async (req: Request): Promise<Response> => {
  if (req.method !== "POST") {
    return json({ error: "Method not allowed" }, 405);
  }
  if (!KOFI_TOKEN) {
    console.error("payment-webhook-kofi: KOFI_VERIFICATION_TOKEN not configured");
    return json({ error: "Webhook not configured" }, 500);
  }

  // Ko-fi sends form-encoded `data=<json>`. Tolerate a raw JSON body too.
  let payload: Record<string, unknown>;
  try {
    const contentType = req.headers.get("content-type") ?? "";
    const text = await req.text();
    if (contentType.includes("application/json")) {
      payload = JSON.parse(text);
    } else {
      const form = new URLSearchParams(text);
      const data = form.get("data");
      if (!data) return json({ error: "Missing data field" }, 400);
      payload = JSON.parse(data);
    }
  } catch {
    return json({ error: "Invalid payload" }, 400);
  }

  if (!timingSafeEqual(String(payload.verification_token ?? ""), KOFI_TOKEN)) {
    console.warn("payment-webhook-kofi: verification token mismatch");
    return json({ error: "Invalid verification token" }, 403);
  }

  const type = String(payload.type ?? "");
  const isSubscriptionPayment =
    payload.is_subscription_payment === true || payload.is_subscription_payment === "true";
  if (type !== "Donation" || isSubscriptionPayment) {
    console.log(`payment-webhook-kofi: skipping non-one-time event type=${type}`);
    return json({ ok: true, skipped: true });
  }

  const providerPid = String(payload.kofi_transaction_id ?? payload.message_id ?? "");
  if (!providerPid) {
    return json({ error: "Missing transaction id" }, 400);
  }

  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false },
  });

  // Idempotency first: a retried delivery with the same transaction id
  // must not duplicate rows or re-run side effects.
  const { data: existing } = await admin
    .from("supporter_payments")
    .select("id")
    .eq("provider", "kofi")
    .eq("provider_payment_id", providerPid)
    .maybeSingle();
  if (existing) {
    return json({ ok: true, duplicate: true });
  }

  // Resolve the ArchEclipse user via the single-use link code in the message.
  let userId: string | null = null;
  const code = extractCode(payload.message);
  if (code) {
    const { data: link } = await admin
      .from("kofi_link_codes")
      .select("user_id, used, expires_at")
      .eq("code", code)
      .maybeSingle();
    if (link && !link.used && new Date(String(link.expires_at)).getTime() > Date.now()) {
      userId = link.user_id;
      await admin.from("kofi_link_codes").update({ used: true }).eq("code", code);
    } else {
      console.log(`payment-webhook-kofi: link code ${code} invalid/expired/used`);
    }
  }

  // Never persist our own verification secret.
  const { verification_token: _drop, ...rest } = payload;

  const amount = payload.amount != null && payload.amount !== "" ? Number(payload.amount) : null;

  const { error: insertError } = await admin.from("supporter_payments").insert({
    user_id: userId,
    provider: "kofi",
    provider_payment_id: providerPid,
    amount: Number.isFinite(amount) ? amount : null,
    currency: payload.currency != null ? String(payload.currency) : null,
    status: "finished",
    donor_email: payload.email != null ? String(payload.email) : null,
    raw: rest,
  });

  if (insertError) {
    // Lost race with a concurrent duplicate delivery: treat as idempotent.
    if (String(insertError.message).includes("duplicate")) {
      return json({ ok: true, duplicate: true });
    }
    console.error("payment-webhook-kofi: insert failed", insertError.message);
    // Non-duplicate storage failure -> non-2xx so Ko-fi retries with the
    // same message_id (safe: insert is idempotent on retry).
    return json({ error: "Storage failed" }, 500);
  }

  console.log(
    `payment-webhook-kofi: donation ${providerPid} recorded` +
      (userId ? ` for user ${userId}` : " UNCLAIMED (no valid link code)"),
  );
  return json({ ok: true, attributed: userId !== null });
});
